from .contact_thanks_view import ContactThanksView
from .contact_view import ContactView
from .dessert_view import DessertView
from .drink_view import DrinkView
from .food_view import FoodView
from .home_view import HomeView
from .lunch_view import LunchView
from .news_archive_view import NewsArchiveView
from .news_detail_view import NewsDetailView
from .recruit_view import RecruitView
