# Generated by Django 6.0.3 on 2026-04-11 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('image', models.ImageField(blank=True, help_text='写真がない記事は空のままで登録できます。', null=True, upload_to='news/', verbose_name='写真')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='公開日時')),
                ('is_published', models.BooleanField(default=True, verbose_name='公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-published_at', '-id'],
            },
        ),
    ]
