# Generated by Django 6.0.3 on 2026-04-11 03:47

import nishimuraya.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishimuraya', '0003_alter_newsarticle_publish_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, help_text='写真がない記事は空のままで登録できます。', null=True, storage=nishimuraya.storages.NewsStaticImageStorage(), upload_to='news/', verbose_name='写真'),
        ),
    ]
