# Generated by Django 6.0.3 on 2026-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishimuraya', '0004_alter_newsarticle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='電話番号')),
                ('message', models.TextField(verbose_name='お問い合わせ内容')),
                ('is_handled', models.BooleanField(db_index=True, default=False, verbose_name='対応済み')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='対応日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='受付日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '問い合わせ',
                'verbose_name_plural': '問い合わせ',
                'ordering': ['is_handled', '-created_at', '-id'],
            },
        ),
    ]
