# Generated by Django 6.0.3 on 2026-07-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nishimuraya', '0006_repair_contact_inquiry_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, help_text='写真がない記事は空のままで登録できます。', null=True, upload_to='news/', verbose_name='写真'),
        ),
    ]
