from django.urls import path, re_path
from django.views.generic import RedirectView

from .views import (
    ContactThanksView,
    ContactView,
    ContactInquiryDetailView,
    ContactInquiryListView,
    ContactInquiryStatusView,
    ContactInquiryToggleHandledView,
    DessertView,
    DrinkView,
    FoodView,
    HomeView,
    LegacyNewsDetailRedirectView,
    LunchView,
    NewsCreateView,
    NewsArchiveView,
    NewsDeleteView,
    NewsDetailView,
    NewsDraftListView,
    NewsPreviewView,
    NewsUpdateView,
    RecruitView,
    StaffLoginRedirectView,
    StaffLoginView,
    StaffLogoutView,
)

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("index/", RedirectView.as_view(pattern_name="home", permanent=True), name="index"),
    path("staff/", StaffLoginRedirectView.as_view(), name="staff_entry"),
    path("staff/login/", StaffLoginView.as_view(), name="staff_login"),
    path("staff/logout/", StaffLogoutView.as_view(), name="staff_logout"),
    path("staff/contact-inquiries/", ContactInquiryListView.as_view(), name="contact_inquiry_list"),
    path("staff/contact-inquiries/status/", ContactInquiryStatusView.as_view(), name="contact_inquiry_status"),
    path("staff/contact-inquiries/<int:pk>/", ContactInquiryDetailView.as_view(), name="contact_inquiry_detail"),
    path("staff/contact-inquiries/<int:pk>/toggle/", ContactInquiryToggleHandledView.as_view(), name="contact_inquiry_toggle"),
    path("food/", FoodView.as_view(), name="food"),
    path("drink/", DrinkView.as_view(), name="drink"),
    path("dessert/", DessertView.as_view(), name="dessert"),
    path("lunch/", LunchView.as_view(), name="lunch"),
    path("recruit/", RecruitView.as_view(), name="recruit"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("contact-thanks/", ContactThanksView.as_view(), name="contact_thanks"),
    path("news/", NewsArchiveView.as_view(), name="news_archive"),
    path("news/drafts/", NewsDraftListView.as_view(), name="news_drafts"),
    path("news/create/", NewsCreateView.as_view(), name="news_create"),
    path("news/preview/<str:preview_token>/", NewsPreviewView.as_view(), name="news_preview"),
    re_path(r"^news/(?P<legacy_slug>news-\d{8}-\d+)/$",LegacyNewsDetailRedirectView.as_view(),name="legacy_news_detail",),
    path("news/<str:url_key>/", NewsDetailView.as_view(), name="news_detail"),
    path("news/<str:url_key>/edit/", NewsUpdateView.as_view(), name="news_update"),
    path("news/<str:url_key>/delete/", NewsDeleteView.as_view(), name="news_delete"),
]
